---

# Copyright 2016 David Stanek <dstanek@dstanek.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: install common software packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ developer_common_packages }}"

- name: include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: install OS specific software packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ developer_os_packages }}"

- name: add a user account
  user:
    name: "{{ developer_username }}"
    comment: "{{ developer_fullname }}"
    groups: "{{ developer_sudo_group }}"
    shell: /bin/zsh
    append: yes
    state: present

- name: add user to sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "{{ developer_username }} ALL=(ALL) NOPASSWD: ALL"
    state: present

- name: allow SSH forwarding to survive a sudo
  lineinfile:
    dest: /etc/sudoers
    line: Defaults env_keep+=SSH_AUTH_SOCK
    state: present

- name: add authorized SSH public keys for user
  authorized_key:
    user: "{{ developer_username }}"
    key: "{{ lookup('file', item)}}"
    state: present
  with_items: "{{ developer_authorized_keyfiles }}"

- name: install git-review
  pip:
    name: git-review
    state: latest

- name: install SSH config
  template:
    src: ssh_config.j2
    dest: "{{ developer_home_directory }}/{{ developer_username }}/.ssh/config"
    owner: "{{ developer_username }}"
    group: "{{ developer_groupname }}"
    mode: 0600
